### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/thumbnails-readme#12]
When README is generated, the hyperlinks point to the thumbnails and not the location of the source. Can we apply this fix easily so that when the user clicks on the image in README is located in the original and not thumbnail?

**Comment by firefly-cpp** [comment]
@KukovecRok

**Comment by KukovecRok** [comment]
Will check, but this is an issue I've thought about before. The link is the path to an image. If the link is changed, the image is not shown.
With other words: README.md must have the path to thumbnail image.
